feat: support default-cargo-crates

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -4,5 +4,31 @@ script_dir=$(dirname "${BASH_SOURCE[0]}")
 # shellcheck source=/dev/null
 . "$script_dir/exec-env"
 
-curl --fail --silent --show-error https://sh.rustup.rs \
-| sh -s -- -y --no-modify-path --default-toolchain "$ASDF_INSTALL_VERSION"
+install_rust() {
+    curl --fail --silent --show-error https://sh.rustup.rs \
+    | sh -s -- -y --no-modify-path --default-toolchain "$ASDF_INSTALL_VERSION"
+}
+
+install_default_cargo_crates() {
+  local default_cargo_crates="${HOME}/.default-cargo-crates"
+
+  if [ ! -f $default_cargo_crates ]; then return; fi
+
+  cat "$default_cargo_crates" | while read -r line; do
+    name=$(echo "$line" | \
+      sed 's|\(.*\) //.*$|\1|' | \ # handle comments after crate name
+      sed -E 's|^[[:space:]]*//.*||') # handle full line comments
+
+    if [ -z $name ]; then continue ; fi
+    echo -ne "\nInstalling \033[33m${name}\033[39m cargo crate... "
+    PATH="$ASDF_INSTALL_PATH/bin:$PATH" cargo install $name > /dev/null && rc=$? || rc=$?
+    if [[ $rc -eq 0 ]]; then
+      echo -e "\033[32mSUCCESS\033[39m"
+    else
+      echo -e "\033[31mFAIL\033[39m"
+    fi
+  done
+}
+
+install_rust
+install_default_cargo_crates
